### PR TITLE
Italian strings

### PR DESCRIPTION
**Pull request by xicciodj**

### CODE REVIEW

**Comment by Mygod** [comment]
Thanks!

**Comment by Mygod** [comment]
Can you review changes I made in 1d97923? If everything looks good, I will merge this.

**Comment by xicciodj** [comment]
Everything looks good, except for donations__thanks_dialog which should be "Grazie per la tua donazione!\nLo apprezzo molto!"

**Comment by Mygod** [comment]
Thanks! I will merge this before next release. Feel free to make changes meanwhile.

**Pull request merged**
