### PR TITLE
Fix android Q can't start Repeater in the background

### PR DESCRIPTION
**Pull request by qwe7002**
Fix android Q can't start Repeater in the background

### CODE REVIEW

**Comment by Mygod** [comment]
Interesting. Have you tested the fix?

**Comment by qwe7002** [comment]
Yes, I have already tested it. On Android Q, location permissions are restricted. The P2P Group can be created normally only when the activity is in the foreground.

**Comment by Mygod** [comment]
Thank you for your suggested fix, however, this can be fixed without requesting background location permission. Please test out e790e513e18666f82d371b4e2fdbb357d102ca94 and see if it fixes it for you.

**Comment by qwe7002** [comment]
This fix can be used, thank you very much!

**Comment by Mygod** [comment]
Fixed in v2.6.3. Thanks again!

**Pull request closed without merging**
