### PR TITLE
Add Chinese(Traditional) ZH-TW

### PR DESCRIPTION
**Pull request by bluehomewu**

### CODE REVIEW

**Comment by Mygod** [comment]
Thanks! I'll merge it for the next release.

**Comment by bluehomewu** [comment]
> Thanks! I'll merge it for the next release.

Why my upload always write "Some Checks were not successful"?
Can you help me to find something wrong?
Thanks.
https://circleci.com/gh/Mygod/VPNHotspot/363?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Mygod** [comment]
Don't worry about passing CI builds. I will take care of that

**Comment by bluehomewu** [comment]
Oh.Great.
Thanks.

**Comment by Mygod** [comment]
Hi again, please review my suggested changes. Feel free to make further edits. Just let me know when you are done and we can roll out the next release!

Some change I did not commit but I would still like to bring up here so that you can decide for me: [AOSP uses "無線基地台" instead of "熱點" for "hotspot" as translation](https://android.googlesource.com/platform/packages/apps/Settings/+/be651d3/res/values-zh-rTW/strings.xml#1021).

Thanks again for your translation!

**Comment by bluehomewu** [comment]
> Hi again, please review my suggested changes. Feel free to make further edits. Just let me know when you are done and we can roll out the next release!
> 
> Some change I did not commit but I would still like to bring up here so that you can decide for me: [AOSP uses "無線基地台" instead of "熱點" for "hotspot" as translation](https://android.googlesource.com/platform/packages/apps/Settings/+/be651d3/res/values-zh-rTW/strings.xml#1021).
> 
> Thanks again for your translation!

Thank you for your remind.
I just changed hotspot translation.

**Comment by Mygod** [comment]
Cool! Feel free to make any changes. I will make a new release tomorrow.

**Comment by bluehomewu** [comment]
> Cool! Feel free to make any changes. I will make a new release tomorrow.

That's so great.
I can't wait to update app.

**Comment by Mygod** [comment]
v2.8.1 is available everywhere now except for Google play who needs to approve the rollout.

**Comment by bluehomewu** [comment]
> v2.8.1 is available everywhere now except for Google play who needs to approve the rollout.

Oh.No.
I just translate something wrong.
I'm so sorry about that.
I had fix error on my page.

**Comment by Mygod** [comment]
Hi, please use suggest change (pen icon) on the [strings.xml in this repo](https://github.com/Mygod/VPNHotspot/blob/master/mobile/src/main/res/values-zh-rTW/strings.xml). I will merge your translations in the next update.

**Comment by Mygod** [comment]
An easy way could be to use the suggest change and copy the entire strings.xml from your repo.

**Comment by bluehomewu** [comment]
> Hi, please use suggest change (pen icon) on the [strings.xml in this repo](https://github.com/Mygod/VPNHotspot/blob/master/mobile/src/main/res/values-zh-rTW/strings.xml). I will merge your translations in the next update.

I have re-edited and fixed the error.

**Comment by Mygod** [comment]
Could you use the suggest change function? It will create another pull request in this repo so that we can review it.

**Comment by bluehomewu** [comment]
> Could you use the suggest change function? It will create another pull request in this repo so that we can review it.
I don't know where can I kick it.
Can you teach me.
Sorry about that.

**Comment by Mygod** [comment]
Of course. Click the link above and click the edit button from there. This way I can review your changes.

**Comment by Mygod** [comment]
@bluehomewu Oh I found that you already did that but you forgot to submit a pull request. Fortunately, this part I can do for you. Please see #150 for my comments on your change.

**Comment by bluehomewu** [comment]
> @bluehomewu Oh I found that you already did that but you forgot to submit a pull request. Fortunately, this part I can do for you. Please see #150 for my comments on your change.

Ok.I see.
I will fix it today.
This one is mine first translate app,I'm so exciting.
Thanks a lot.

**Pull request merged**
