### PR TITLE
正规化了部分过于抖机灵的汉化，更换了连字符“-”和不统一的逗号“，”/","。

### PR DESCRIPTION
**Pull request by Sodium-Aluminate**

### CODE REVIEW

**Comment by Mygod** [comment]
https://www.fileformat.info/info/unicode/char/2011/index.htm

**Comment by Sodium-Aluminate** [comment]
> https://www.fileformat.info/info/unicode/char/2011/index.htm

oops got it.

**Comment by Mygod** [comment]
For the rest of your suggestions, I prefer my translations still. Thanks anyway!

**Comment by Sodium-Aluminate** [comment]
> For the rest of your suggestions, I prefer my translations still. Thanks anyway!

all right...

**Pull request closed without merging**
